### ISSUE TITLE
Refactor getData()

### ISSUE THREAD

**Issue by mschlosser22** [ckschlosser/movie-api#6]
@ckschlosser could you refactor the [getData()](https://github.com/ckschlosser/movie-api/blob/eb83c804531faa15ed2611f7b14e99061ad9bc85/src/components/Content.js#L27) method in [/src/components/Content.js](https://github.com/ckschlosser/movie-api/blob/eb83c804531faa15ed2611f7b14e99061ad9bc85/src/components/Content.js)?

Maybe create a config/mapping `movieDataConfig.json` file like:

````
{
   "movieData":[
      {
         "genre":"Popular",
         "path":"/discover/movie?sort_by=popularity.desc"
      },
      {
         "genre":"Theatre",
         "path":"/movie?primary_release_date.gte=2014-09-15&primary_release_date.lte=2014-10-22"
      }
   ]
}
````

Then `import movieData from "./movieDataConfig.json";` into `Content.js` and loop through then and also set a default.

**Comment by ckschlosser** [comment]
Added the config.json and refactored getData method. Application is fully functional and pushed the changes.
